/**
 * AtlasTextGeneration — commit messages, PR content, branch names and thread
 * titles generated by an Atlas node.
 *
 * The CLI-backed providers each stand up a session runtime for these, because a
 * subprocess is the only way to reach their model. Atlas already exposes a
 * one-shot RPC — `POST /Agent/{id}/run` drives a run to completion and returns
 * the answer inline — so every operation here is one HTTP call plus a decode.
 *
 * @module AtlasTextGeneration
 */
import { type AtlasSettings, TextGenerationError } from "@t3tools/contracts";
import { extractJsonObject } from "@t3tools/shared/schemaJson";
import * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { HttpClient } from "effect/unstable/http";

import { atlasRun } from "../provider/Layers/AtlasClient.ts";
import * as TextGeneration from "./TextGeneration.ts";
import {
  buildBranchNamePrompt,
  buildCommitMessagePrompt,
  buildPrContentPrompt,
  buildThreadTitlePrompt,
} from "./TextGenerationPrompts.ts";
import {
  sanitizeCommitSubject,
  sanitizePrTitle,
  sanitizeThreadTitle,
} from "./TextGenerationUtils.ts";

type AtlasTextOperation =
  | "generateCommitMessage"
  | "generatePrContent"
  | "generateBranchName"
  | "generateThreadTitle";

export const makeAtlasTextGeneration = Effect.fn("makeAtlasTextGeneration")(function* (
  config: AtlasSettings,
) {
  // Captured once. The service contract declares `R = never`, so the client is
  // provided here rather than leaking a requirement to every caller.
  const httpClient = yield* HttpClient.HttpClient;
  let sequence = 0;
  /**
   * One prompt, one run, one decoded object.
   *
   * A fresh run id per call keeps these off the user's warm thread — a commit
   * message should not appear in the conversation transcript.
   */
  const runAtlasJson = <S extends Schema.Top>({
    operation,
    prompt,
    outputSchemaJson,
  }: {
    readonly operation: AtlasTextOperation;
    readonly prompt: string;
    readonly outputSchemaJson: S;
  }): Effect.Effect<S["Type"], TextGenerationError, S["DecodingServices"]> =>
    Effect.gen(function* () {
      const answer = yield* atlasRun({
        baseUrl: config.baseUrl,
        runId: `textgen-${operation}-${(sequence += 1)}`,
        plugin: config.plugin,
        task: prompt,
      }).pipe(
        Effect.provideService(HttpClient.HttpClient, httpClient),
        Effect.mapError(
          (cause) =>
            new TextGenerationError({
              operation,
              detail: `Atlas node did not answer: ${cause.detail}`,
              cause,
            }),
        ),
      );

      // Atlas answers in prose, so the model's JSON has to be lifted out of
      // whatever it wrapped it in. `extractJsonObject` returns a STRING and
      // falls back to the trimmed input when it finds no object at all, so the
      // "no JSON" case has to be detected here rather than by a null check.
      const extracted = extractJsonObject(answer).trim();
      if (!extracted.startsWith("{")) {
        return yield* Effect.fail(
          new TextGenerationError({
            operation,
            detail: "Atlas returned no JSON object for a structured generation request.",
          }),
        );
      }

      const decodeOutput = Schema.decodeEffect(Schema.fromJsonString(outputSchemaJson));
      return yield* decodeOutput(extracted).pipe(
        Effect.mapError(
          (cause) =>
            new TextGenerationError({
              operation,
              detail: "Atlas returned JSON that did not match the expected shape.",
              cause,
            }),
        ),
      );
    });

  const generateCommitMessage: TextGeneration.TextGeneration["Service"]["generateCommitMessage"] =
    Effect.fn("AtlasTextGeneration.generateCommitMessage")(function* (input) {
      const { prompt, outputSchema } = buildCommitMessagePrompt({
        branch: input.branch,
        stagedSummary: input.stagedSummary,
        stagedPatch: input.stagedPatch,
        includeBranch: input.includeBranch ?? false,
      });
      const generated = yield* runAtlasJson({
        operation: "generateCommitMessage",
        prompt,
        outputSchemaJson: outputSchema,
      });
      // `includeBranch` is a runtime flag, so the prompt builder's return type is
      // narrowed to the no-branch shape. The branch field is present at runtime
      // exactly when the flag was set.
      const withBranch = generated as { subject: string; body: string; branch?: string };
      return {
        subject: sanitizeCommitSubject(withBranch.subject),
        body: withBranch.body ?? "",
        ...(withBranch.branch ? { branch: withBranch.branch } : {}),
      } satisfies TextGeneration.CommitMessageGenerationResult;
    });

  const generatePrContent: TextGeneration.TextGeneration["Service"]["generatePrContent"] =
    Effect.fn("AtlasTextGeneration.generatePrContent")(function* (input) {
      const { prompt, outputSchema } = buildPrContentPrompt({
        baseBranch: input.baseBranch,
        headBranch: input.headBranch,
        commitSummary: input.commitSummary,
        diffSummary: input.diffSummary,
        diffPatch: input.diffPatch,
      });
      const generated = yield* runAtlasJson({
        operation: "generatePrContent",
        prompt,
        outputSchemaJson: outputSchema,
      });
      return {
        title: sanitizePrTitle(generated.title),
        body: generated.body,
      } satisfies TextGeneration.PrContentGenerationResult;
    });

  const generateBranchName: TextGeneration.TextGeneration["Service"]["generateBranchName"] =
    Effect.fn("AtlasTextGeneration.generateBranchName")(function* (input) {
      const { prompt, outputSchema } = buildBranchNamePrompt({
        message: input.message,
        attachments: input.attachments,
      });
      const generated = yield* runAtlasJson({
        operation: "generateBranchName",
        prompt,
        outputSchemaJson: outputSchema,
      });
      return { branch: generated.branch } satisfies TextGeneration.BranchNameGenerationResult;
    });

  const generateThreadTitle: TextGeneration.TextGeneration["Service"]["generateThreadTitle"] =
    Effect.fn("AtlasTextGeneration.generateThreadTitle")(function* (input) {
      const { prompt, outputSchema } = buildThreadTitlePrompt({
        message: input.message,
        attachments: input.attachments,
      });
      const generated = yield* runAtlasJson({
        operation: "generateThreadTitle",
        prompt,
        outputSchemaJson: outputSchema,
      });
      return {
        title: sanitizeThreadTitle(generated.title),
      } satisfies TextGeneration.ThreadTitleGenerationResult;
    });

  return {
    generateCommitMessage,
    generatePrContent,
    generateBranchName,
    generateThreadTitle,
  } satisfies TextGeneration.TextGeneration["Service"];
});
