#!/usr/bin/env node

/**
 * Generates Effect Schemas for the Atlas wire contract from the artifact Atlas itself
 * emits and drift-guards (`atlas-rs/crates/atlas-protocol/schema/atlas-protocol.flat.json`,
 * regenerated by `cargo run -p atlas-protocol --bin emit-schema -- --flat`).
 *
 * Modeled on `packages/effect-acp/scripts/generate.ts`, minus its download half: the
 * upstream here is a sibling repository on disk, and a checked-in snapshot of the artifact
 * keeps this repo self-contained — the diff on that snapshot IS the wire change.
 *
 * Atlas is the schema owner (doc 12 §9). Nothing in `src/atlas/_generated` is authored.
 */

import * as NodeRuntime from "@effect/platform-node/NodeRuntime";
import * as NodeServices from "@effect/platform-node/NodeServices";
import { make as makeJsonSchemaGenerator } from "@effect/openapi-generator/JsonSchemaGenerator";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Layer from "effect/Layer";
import * as Logger from "effect/Logger";
import * as Path from "effect/Path";
import * as Schema from "effect/Schema";
import { Command, Flag } from "effect/unstable/cli";
import { ChildProcess, ChildProcessSpawner } from "effect/unstable/process";

interface GenerateCommandError {
  readonly _tag: "GenerateCommandError";
  readonly message: string;
}

const FlatContractSchema = Schema.Struct({
  protocolVersion: Schema.Number,
  $defs: Schema.Record(Schema.String, Schema.Json),
});
const decodeFlatContract = Schema.decodeEffect(Schema.fromJsonString(FlatContractSchema));

const getPaths = Effect.fn("getPaths")(function* (upstreamOverride: string | undefined) {
  const path = yield* Path.Path;
  const generatedDir = path.join(import.meta.dirname, "..", "src", "atlas", "_generated");
  // scripts → contracts → packages → t3code → git-forks → atlas
  const defaultUpstream = path.join(
    import.meta.dirname,
    "..",
    "..",
    "..",
    "..",
    "..",
    "atlas-rs",
    "crates",
    "atlas-protocol",
    "schema",
    "atlas-protocol.flat.json",
  );
  return {
    generatedDir,
    upstreamPath: upstreamOverride ?? defaultUpstream,
    snapshotPath: path.join(generatedDir, "atlas-protocol.flat.json"),
    schemaOutputPath: path.join(generatedDir, "schema.gen.ts"),
    metaOutputPath: path.join(generatedDir, "meta.gen.ts"),
  };
});

function collectSchemaEntries(
  chunk: string,
): ReadonlyArray<{ readonly name: string; readonly code: string }> {
  const lines = chunk
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("//"));
  const entries: Array<{ name: string; code: string }> = [];

  for (let index = 0; index < lines.length; index += 1) {
    const typeLine = lines[index];
    if (!typeLine?.startsWith("export type ")) {
      continue;
    }
    const constLine = lines[index + 1];
    if (!constLine?.startsWith("export const ")) {
      throw new Error(`Malformed generator output near: ${typeLine}`);
    }
    const match = /^export type ([A-Za-z0-9_]+)/.exec(typeLine);
    if (!match?.[1]) {
      throw new Error(`Could not extract schema name from: ${typeLine}`);
    }
    entries.push({ name: match[1], code: `${typeLine}\n${constLine}` });
    index += 1;
  }

  return entries;
}

/** Same normalization the ACP generator applies: `type: [T, "null"]` → `anyOf` with null. */
function normalizeNullableTypes(value: Schema.Json): Schema.Json {
  if (Array.isArray(value)) {
    return value.map(normalizeNullableTypes);
  }
  if (value === null || typeof value !== "object") {
    return value;
  }
  const normalizedObject = Object.fromEntries(
    Object.entries(value).map(([key, child]) => [key, normalizeNullableTypes(child)]),
  ) as Record<string, Schema.Json>;
  const typeValue = normalizedObject.type;
  if (!Array.isArray(typeValue)) {
    return normalizedObject;
  }
  const normalizedTypes = typeValue.filter((entry): entry is string => typeof entry === "string");
  if (normalizedTypes.length !== typeValue.length || !normalizedTypes.includes("null")) {
    return normalizedObject;
  }
  const nonNullTypes = normalizedTypes.filter((entry) => entry !== "null");
  if (nonNullTypes.length !== 1) {
    return normalizedObject;
  }
  const nonNullType = nonNullTypes[0]!;
  const nextObject: Record<string, Schema.Json> = {};
  for (const [key, child] of Object.entries(normalizedObject)) {
    // schemars stamps `"default": null` on nullable fields. After the split that default
    // would ride the NON-null branch, where Effect types `default` as the branch's own
    // type — `null` is not a `number`. A null default on an optional field carries no
    // decode semantics, so drop it rather than mistype it.
    if (key === "type" || (key === "default" && child === null)) {
      continue;
    }
    nextObject[key] = child;
  }
  return { anyOf: [{ ...nextObject, type: nonNullType }, { type: "null" }] };
}

const generate = Effect.fn("generate")(function* (upstreamOverride: string | undefined) {
  const fs = yield* FileSystem.FileSystem;
  const paths = yield* getPaths(upstreamOverride);

  yield* fs.makeDirectory(paths.generatedDir, { recursive: true });

  const raw = yield* fs.readFileString(paths.upstreamPath);
  const contract = yield* decodeFlatContract(raw);

  const normalizedDefinitions = Object.fromEntries(
    Object.entries(contract.$defs).map(([name, schema]) => [name, normalizeNullableTypes(schema)]),
  );
  const sortedEntries = Object.entries(normalizedDefinitions).toSorted(([left], [right]) =>
    left.localeCompare(right),
  );

  const generator = makeJsonSchemaGenerator();
  for (const [name, schema] of sortedEntries) {
    generator.addSchema(name, schema as never);
  }
  const output = generator.generate("openapi-3.1", normalizedDefinitions as never, false).trim();

  const generatedEntries = new Map<string, string>();
  for (const entry of collectSchemaEntries(output)) {
    if (!generatedEntries.has(entry.name)) {
      generatedEntries.set(entry.name, entry.code);
    }
  }
  if (generatedEntries.size === 0) {
    return yield* Effect.fail<GenerateCommandError>({
      _tag: "GenerateCommandError",
      message: "generator produced no schemas — is the flat artifact empty?",
    });
  }

  const prelude = [
    "// Generated from atlas-protocol (the Atlas wire contract). Do not edit manually.",
    `// Atlas protocolVersion: ${contract.protocolVersion}`,
    "// Regenerate: (in atlas-rs) cargo run -p atlas-protocol --bin emit-schema -- --flat",
    "//             then here: pnpm --filter @t3tools/contracts generate:atlas",
    "",
  ];

  const schemaOutput = [
    ...prelude,
    'import * as Schema from "effect/Schema";',
    "",
    [...generatedEntries.values()].join("\n\n"),
    "",
  ].join("\n");

  const metaOutput = [
    ...prelude,
    `export const ATLAS_PROTOCOL_VERSION = ${contract.protocolVersion} as const;`,
    "",
  ].join("\n");

  yield* fs.writeFileString(paths.snapshotPath, raw);
  yield* fs.writeFileString(paths.schemaOutputPath, schemaOutput);
  yield* fs.writeFileString(paths.metaOutputPath, metaOutput);
  yield* Effect.log(
    `Generated ${generatedEntries.size} Atlas schemas (protocolVersion ${contract.protocolVersion})`,
  );

  yield* Effect.service(ChildProcessSpawner.ChildProcessSpawner).pipe(
    Effect.flatMap((spawner) =>
      spawner.spawn(ChildProcess.make("npx", ["vp", "fmt", paths.generatedDir])),
    ),
    Effect.flatMap((child) => child.exitCode),
    Effect.tap((code) =>
      code === 0
        ? Effect.void
        : Effect.fail<GenerateCommandError>({
            _tag: "GenerateCommandError",
            message: `oxfmt failed with exit code ${code}`,
          }),
    ),
  );
});

const generateCommand = Command.make(
  "generate-atlas",
  {
    upstream: Flag.string("upstream").pipe(Flag.optional),
  },
  ({ upstream }) => generate(upstream._tag === "Some" ? upstream.value : undefined),
).pipe(Command.withDescription("Generate Atlas wire schemas from atlas-protocol's flat artifact."));

const runtimeLayer = Layer.mergeAll(Logger.layer([Logger.consolePretty()]), NodeServices.layer);

Command.run(generateCommand, { version: "0.0.0" }).pipe(
  Effect.scoped,
  Effect.provide(runtimeLayer),
  NodeRuntime.runMain,
);
